"""内建模型目录（从 catalog.py 抽离）。

BUILTIN_CATALOG 是内建模型唯一真相来源，catalog.py 与 catalog_db.py 均引用此处；
catalog_db 启动时将条目物化为 ``catalog_entries(kind='builtin')``，
``catalog.build_catalog()`` 优先从 DB 读取、DB 为空时回退本常量。"""

from __future__ import annotations

from typing import Any

# cost 单位：USD / 每 1M tokens。价格未知记 0（opencode 当前即硬编码 0 的成本态）。
BUILTIN_CATALOG: list[dict[str, Any]] = [
    {
        "id": "deepseek/deepseek-v4-flash",
        "provider": "deepseek",
        "family": "deepseek-v4",
        "name": "DeepSeek V4 Flash",
        "description": "轻量高速模型，日常问答与多智能体调度首选，速度与质量兼顾",
        "capabilities": {"tool_use": True, "vision": False, "reasoning": True},
        "context_length": 160000,
        "limits": {"max_output_tokens": 8192},
        "cost": {"input_per_1m": 0.27, "output_per_1m": 1.10,
                 "cache_read_per_1m": 0.07, "cache_write_per_1m": 0.0},
        "default": True,
    },
    {
        "id": "deepseek/deepseek-v4-pro",
        "provider": "deepseek",
        "family": "deepseek-v4",
        "name": "DeepSeek V4 Pro",
        "description": "旗舰推理模型，复杂任务、长文本与深度分析能力更强",
        "capabilities": {"tool_use": True, "vision": False, "reasoning": True},
        "context_length": 160000,
        "limits": {"max_output_tokens": 8192},
        "cost": {"input_per_1m": 0.27, "output_per_1m": 1.10,
                 "cache_read_per_1m": 0.07, "cache_write_per_1m": 0.0},
    },
    {
        "id": "openai/gpt-4o",
        "provider": "openai",
        "family": "gpt-4o",
        "name": "OpenAI GPT-4o",
        "description": "OpenAI 多模态旗舰模型，图文理解与通用任务表现均衡",
        "capabilities": {"tool_use": True, "vision": True, "reasoning": False},
        "context_length": 128000,
        "limits": {"max_output_tokens": 16384},
        "cost": {"input_per_1m": 2.50, "output_per_1m": 10.00,
                 "cache_read_per_1m": 1.25, "cache_write_per_1m": 0.0},
    },
    {
        "id": "openai/gpt-4o-mini",
        "provider": "openai",
        "family": "gpt-4o",
        "name": "OpenAI GPT-4o-mini",
        "description": "GPT-4o 轻量版，成本更低、响应更快，适合高频简单任务",
        "capabilities": {"tool_use": True, "vision": True, "reasoning": False},
        "context_length": 128000,
        "limits": {"max_output_tokens": 16384},
        "cost": {"input_per_1m": 0.15, "output_per_1m": 0.60,
                 "cache_read_per_1m": 0.075, "cache_write_per_1m": 0.0},
    },
    {
        "id": "ollama/qwen2.5-coder:latest",
        "provider": "ollama",
        "family": "qwen2.5-coder",
        "name": "Ollama Qwen2.5-Coder",
        "description": "本地代码生成模型，编程与代码任务首选，支持工具调用",
        "capabilities": {"tool_use": True, "vision": False, "reasoning": False},
        "context_length": 32768,
        "limits": {"max_output_tokens": 8192},
        "cost": {"input_per_1m": 0.0, "output_per_1m": 0.0,
                 "cache_read_per_1m": 0.0, "cache_write_per_1m": 0.0},
    },
    {
        "id": "ollama/qwen2.5:7b",
        "provider": "ollama",
        "family": "qwen2.5",
        "name": "Ollama Qwen2.5 7B",
        "description": "通义千问轻量版，中文理解与生成能力均衡，支持工具调用",
        "capabilities": {"tool_use": True, "vision": False, "reasoning": False},
        "context_length": 32768,
        "limits": {"max_output_tokens": 8192},
        "cost": {"input_per_1m": 0.0, "output_per_1m": 0.0,
                 "cache_read_per_1m": 0.0, "cache_write_per_1m": 0.0},
    },
    {
        "id": "ollama/qwen2.5:14b",
        "provider": "ollama",
        "family": "qwen2.5",
        "name": "Ollama Qwen2.5 14B",
        "description": "通义千问中型版，复杂推理与长文本处理能力更强，支持工具调用",
        "capabilities": {"tool_use": True, "vision": False, "reasoning": False},
        "context_length": 32768,
        "limits": {"max_output_tokens": 8192},
        "cost": {"input_per_1m": 0.0, "output_per_1m": 0.0,
                 "cache_read_per_1m": 0.0, "cache_write_per_1m": 0.0},
    },
    {
        "id": "ollama/qwen2.5:32b",
        "provider": "ollama",
        "family": "qwen2.5",
        "name": "Ollama Qwen2.5 32B",
        "description": "通义千问大型版，高质量生成与深度分析，支持工具调用",
        "capabilities": {"tool_use": True, "vision": False, "reasoning": False},
        "context_length": 32768,
        "limits": {"max_output_tokens": 8192},
        "cost": {"input_per_1m": 0.0, "output_per_1m": 0.0,
                 "cache_read_per_1m": 0.0, "cache_write_per_1m": 0.0},
    },
    {
        "id": "ollama/codellama:latest",
        "provider": "ollama",
        "family": "codellama",
        "name": "Ollama CodeLlama",
        "description": "Meta 代码专用模型，Python/JavaScript 编程优化",
        "capabilities": {"tool_use": False, "vision": False, "reasoning": False},
        "context_length": 16384,
        "limits": {"max_output_tokens": 4096},
        "cost": {"input_per_1m": 0.0, "output_per_1m": 0.0,
                 "cache_read_per_1m": 0.0, "cache_write_per_1m": 0.0},
    },
    {
        "id": "ollama/llama3.1:latest",
        "provider": "ollama",
        "family": "llama3.1",
        "name": "Ollama Llama 3.1",
        "description": "Meta 最新通用模型，多语言支持与推理能力",
        "capabilities": {"tool_use": False, "vision": False, "reasoning": False},
        "context_length": 131072,
        "limits": {"max_output_tokens": 4096},
        "cost": {"input_per_1m": 0.0, "output_per_1m": 0.0,
                 "cache_read_per_1m": 0.0, "cache_write_per_1m": 0.0},
    },
    {
        "id": "ollama/mistral:latest",
        "provider": "ollama",
        "family": "mistral",
        "name": "Ollama Mistral",
        "description": "轻量高效模型，快速响应与低资源占用",
        "capabilities": {"tool_use": False, "vision": False, "reasoning": False},
        "context_length": 32768,
        "limits": {"max_output_tokens": 4096},
        "cost": {"input_per_1m": 0.0, "output_per_1m": 0.0,
                 "cache_read_per_1m": 0.0, "cache_write_per_1m": 0.0},
    },
    {
        "id": "ollama/olmo-3:7b",
        "provider": "ollama",
        "family": "olmo-3",
        "name": "Ollama OLMo 3 7B",
        "description": "本地开源模型，AI2 OLMo 3，支持工具调用",
        "capabilities": {"tool_use": True, "vision": False, "reasoning": False},
        "context_length": 32768,
        "limits": {"max_output_tokens": 8192},
        "cost": {"input_per_1m": 0.0, "output_per_1m": 0.0,
                 "cache_read_per_1m": 0.0, "cache_write_per_1m": 0.0},
    },
]

ZERO_COST = {
    "input_per_1m": 0.0, "output_per_1m": 0.0,
    "cache_read_per_1m": 0.0, "cache_write_per_1m": 0.0,
}
